name: myspot_02
description: "MySpot second version"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.5.0 # Mapa de Google integrado
  url_launcher: ^6.1.14  # Para abrir mapas
  supabase: ^1.10.25
  image_picker: ^1.1.1
  mime: ^1.0.4
  http: ^1.2.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/Tst.jpg
    - lib/images/coeurdes.jpg
    - lib/images/grutas.jpg
    - lib/images/mountain.jpg
    - assets/icon/app_icon.png
    - lib/images/grutas.jpg
    - assets/data/cities_by_country.json
